version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3-alpine
    container_name: lanie_postgres
    restart: always
    environment:
      POSTGRES_USER: lanie_user
      POSTGRES_PASSWORD: lanie_password
      POSTGRES_DB: lanie_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: lanie_redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  postgres_data:
